# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6OeQmYhA2yFQc_ocWayoS9A-NcNu-Qc
"""

# ================================
# SkillCraft Internship - Task 03
# Decision Tree on Bank Marketing Dataset
# ================================

# ✅ Install & Import Libraries
!pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

sns.set(style="whitegrid", palette="muted")

# ✅ Load Dataset (UCI Bank Marketing Dataset)
url = "https://raw.githubusercontent.com/selva86/datasets/master/bank-full.csv"
data = pd.read_csv(url, sep=';')  # Dataset uses semicolon delimiter

print("Dataset Loaded Successfully ✅")
display(data.head())

# ✅ Basic Info
print("\nDataset Info:")
data.info()

print("\nMissing Values:")
print(data.isnull().sum())

# ✅ Convert categorical to numeric (Label Encoding)
le = LabelEncoder()
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

print("\n✅ Label Encoding Done")
display(data.head())

# ✅ Split Data
X = data.drop("y", axis=1)  # Features
y = data["y"]               # Target (Subscribed: yes/no)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ✅ Model Training
model = DecisionTreeClassifier(max_depth=4, random_state=42)
model.fit(X_train, y_train)

# ✅ Prediction
y_pred = model.predict(X_test)

# ✅ Evaluation
print("\n🔍 Classification Report:")
print(classification_report(y_test, y_pred))

print("\n✅ Accuracy Score:")
print(accuracy_score(y_test, y_pred))

# ✅ Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

# ✅ Visualize Decision Tree
plt.figure(figsize=(16, 10))
plot_tree(model, feature_names=X.columns, class_names=["No", "Yes"], filled=True)
plt.title("Decision Tree Visualization")
plt.show()

print("\n✅ Model Training & Visualization Completed!")